### ISSUE TITLE
Changing uppercase in some components

### ISSUE THREAD

**Issue by ajaen4** [creativetimofficial/now-ui-kit-react#2]
Hi,

I am new to Now UI and I am having trouble editing some titles. For example, I would like to change the capitalization of the NavarBrand component I have in my Navegation bar. I have commented the text-transform field in the css but the text is still in upper case, how can I keep the format in which I put the string in the brand component?

Thanks in advance.

**Comment by einazare** [comment]
Hello there, @ajaen4 ,

We actually do not use css, we use scss, so you need to change inside our scss the styles, instead of the css.
Take a look at the following links:
- https://github.com/creativetimofficial/now-ui-kit-react/blob/master/src/index.js
- https://demos.creative-tim.com/now-ui-kit-react/#/documentation/introduction

My recommendation is to not directly change our scss/css, since when we'll make an update to the product, we might change our styles, and that will make it hard for you to update your project.
Also, please read the following for an easier development with our products:

> The easiest way to make updates is as follows:
> * You create two repositories on a versioning control system (for example GitHub, GitLab, Bitbucket etc.)  - if it's a PRO paid product, we suggest that the repositories to be private
> * On the first repository, you add our product unaltered
> * On the second repository, you add our product and/or develop your project
> * Each time we release a new version of the product at hand, you download again the product, and put it on top of the first repository, the versioning control system (for example GitHub, GitLab, Bitbucket etc.) will tell you all the differences between the versions
> * By using a repository, you can even make new branches for each of our new version, that way, you will always have all the versions

Hope this information is of help. If you have further questions, let us know.

Best,
Manu
